import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ArticleList from "@/components/ArticleList";
import NavigationMenu from "@/components/NavMenu";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid-container">
          <Header
            brandName="住みよい町田"
            tagline="町田での生活を発信していきます。"
          />
          {/* Navigation Menu */}
          <NavigationMenu />

          <div className="main-container">
            {/* Left Sidebar */}
            <aside className="sidebar-left">
              <ArticleList />
            </aside>
            {/* Main Content */}
            <main className="main prose-sm bg-amber-500">{children}</main>

            <aside className="sidebar-right bg-amber-200">
              <p>サイドバー</p>
            </aside>
          </div>
          <footer className="footer bg-gray-200 text-center py-4">
            © 2025 住みよい町田
          </footer>
        </div>
      </body>
    </html>
  );
}
